title: "Gemigit" # title on the main page
database: "gemigit.db" # sqlite3 database file

gemini:
  certificate: "cert.pem" # SSL certificate
  key: "key.pem" # private key
  address: "0.0.0.0" # address to listen on
  port: 1965 # bind port for gemini request
  templates: "./templates/" # templates directory

git:
  https: false # show https instead of http in the repository pages
  domain: "localhost" # domain for the http git request
  address: "0.0.0.0" # address to listen on
  port: 5555 # bind port for http git request

ldap:
  enabled: false # logging using ldap credential
  url: "ldaps://ldap.example.com" # url to the ldap server
  attribute: "cn" # attribute associated with the username
  binding: "ou=users,dc=example,dc=com"

users:
  registration: true # allow registration, will be disabled if ldap is enabled
  session: 1209600 # Number of seconds before disconnecting a user

protection:
  ip: 10 # Maximum connection attempts before the ip is blocked
  account: 30 # Maximum connection attempts before the account is blocked
  reset: 120 # Number of seconds before clearing the block on ip/accounts
