version: '3'
services:
  gemigit:
    build: .
    container_name: gemigit
    ports:
      - "1965:1965"
      - "5555:5555"
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./cert.pem:/app/cert.pem
      - ./key.pem:/app/key.pem
      - ./data:/app/data/